### ISSUE TITLE
Error during trajectory inference

### ISSUE THREAD

**Issue by kverstae** [dynverse/ti_pcreode#2]
```Traceback (most recent call last):
  File "/code/run.py", line 52, in <module>
    mute = True
  File "/pCreode/pcreode/functions.py", line 698, in pCreode
    hi_pl, hi_pl_ind = hierarchical_placement( dens_knn, cen_ind)
  File "/pCreode/pcreode/functions.py", line 284, in hierarchical_placement
    run_dist = get_graph_distance( end_ind, to_ind, graph)
  File "/pCreode/pcreode/functions.py", line 120, in get_graph_distance
    d[ii,:] = graph.shortest_paths( from_ind[ii], to_ind, weights="weight")[0]
igraph._igraph.InternalError: Error at structural_properties.c:5200: cannot run Bellman-Ford algorithm, Negative loop detected while calculating shortest paths```

**Comment by herrinca** [comment]
Thanks for letting me know.... Too much trouble to get a copy of the data set that flagged this error? Would like to try and reproduce.
